### ISSUE TITLE
Move project into organization

### ISSUE THREAD

**Issue by aik099** [console-helpers/jira-api-restclient#111]
The permission system for user accounts is far less flexible, than for organizations on the GitHub. This for example prevents giving full access (include adding web hooks permissions) to a repository, while it's located under user account.

Proposing to move project under existing organization or create new one to allow more advanced configuration and integration with other services, like Scrutinizer CI or CodeCov.

**Comment by aik099** [comment]
@chobie , can you please discuss this with me?

**Comment by aik099** [comment]
@chobie , please respond.

**Comment by chobie** [comment]
@aik099 
I apologize for not getting back to you for such a long time. I will spare the details, but I have been dealing with a serious illness while managing a heavy workload, which made my personal life very difficult.

Regarding the transfer of the repository, I agree if the purpose is to hand over the Issues and PRs.

After checking GitHub's official documentation, I believe it would be smoother in terms of permissions to first transfer the repository to your personal account and then move it to an Organization as needed. If you have any other ideas, please let me know.

**Comment by aik099** [comment]
> I apologize for not getting back to you for such a long time. I will spare the details, but I have been dealing with a serious illness while managing a heavy workload, which made my personal life very difficult.

No need to apologize. 🙂 I hope you're doing well now. God bless you! 


> Regarding the transfer of the repository, I agree if the purpose is to hand over the Issues and PRs.

The purpose is to bring the project back to life. I'm sure other users of this library will have a lot of ideas as well.

> After checking GitHub's official documentation, I believe it would be smoother in terms of permissions to first transfer the repository to your personal account and then move it to an Organization as needed. If you have any other ideas, please let me know.

I've sent you an invitation to the https://github.com/console-helpers organization. Once you accept I'll add `Create Repository` permission (I hope I can find where to do this) and then you can move the repository.

**Comment by aik099** [comment]
> I have joined the Console-Helpers Organization. If I am granted the necessary permissions, I will proceed with transferring the repository.

Can you do the transfer now?
