### ISSUE TITLE
There should be an option to configure timeout with API

### ISSUE THREAD

**Issue by ish1301** [console-helpers/jira-api-restclient#159]
I had to manually set the timeout using below options.

chobie/jira-api-restclient/src/Jira/Api/Client/CurlClient.php

		curl_setopt($curl, CURLOPT_TIMEOUT, 30);
		curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 10);

**Comment by ish1301** [comment]
Here we go, https://github.com/chobie/jira-api-restclient/pull/160

**Comment by aik099** [comment]
Closing in favor of #216.
